Update build-openwrt-using-imagebuilder.yml

diff --git a/.github/workflows/build-openwrt-using-imagebuilder.yml b/.github/workflows/build-openwrt-using-imagebuilder.yml
--- a/.github/workflows/build-openwrt-using-imagebuilder.yml
+++ b/.github/workflows/build-openwrt-using-imagebuilder.yml
@@ -1,27 +1,24 @@
-#=====================================================================================
+#============================================================================================
 # https://github.com/ophub/amlogic-s9xxx-openwrt
-# Description:   Build OpenWrt using ImageBuilder
-# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
-# Download from: https://downloads.openwrt.org/releases
-#                https://downloads.immortalwrt.org/releases
-#=====================================================================================
+# Description: Build OpenWrt system image from source
+#============================================================================================
 
-name: Build OpenWrt using ImageBuilder
+name: Build OpenWrt system image
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      releases_branch:
-        description: "Select the releases branch"
+      source_branch:
+        description: "Select the source branch"
         required: false
-        default: "openwrt:25.12.5"
+        default: "all"
         type: choice
         options:
-          - openwrt:25.12.5
-          - openwrt:24.10.8
-          - immortalwrt:25.12.1
-          - immortalwrt:24.10.6
+          - all
+          - openwrt_main
+          - lede_master
+          - immortalwrt_master
       openwrt_board:
         description: "Select device board"
         required: false
@@ -307,6 +304,19 @@ on:
         description: "Set OpenWrt default IP address."
         required: false
         default: "192.168.1.1"
+      use_ccache:
+        description: "Auto use ccache."
+        required: false
+        default: true
+        type: boolean
+      openwrt_storage:
+        description: "Select image storage type."
+        required: false
+        default: "save"
+        type: choice
+        options:
+          - save
+          - temp
       builder_name:
         description: "Set OpenWrt builder signature."
         required: false
@@ -319,18 +329,48 @@ on:
 
 env:
   TZ: Etc/UTC
-  IMAGEBUILDER_SH: config/imagebuilder/imagebuilder.sh
+  CCACHE_DIR: /builder/openwrt/.ccache
 
 jobs:
+  setup:
+    runs-on: ubuntu-24.04
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Set build matrix based on source_branch input
+        id: set-matrix
+        run: |
+          if [[ "${{ inputs.source_branch }}" == "all" ]]; then
+            MATRIX='{"include":[{"branch":"openwrt_main"},{"branch":"lede_master"},{"branch":"immortalwrt_master"}]}'
+          else
+            MATRIX='{"include":[{"branch":"${{ inputs.source_branch }}"}]}'
+          fi
+          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"
+
   build:
-    runs-on: ubuntu-26.04
+    needs: setup
+    runs-on: ubuntu-24.04
     if: ${{ github.event.repository.owner.id == github.event.sender.id }}
     permissions:
       contents: write
 
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
+
+    name: build-${{ matrix.branch }}
+
+    env:
+      FEEDS_CONF: config/${{ matrix.branch }}/feeds.conf.default
+      CONFIG_FILE: config/${{ matrix.branch }}/config
+      DIY_P1_SH: config/${{ matrix.branch }}/diy-part1.sh
+      DIY_P2_SH: config/${{ matrix.branch }}/diy-part2.sh
+
     steps:
       - name: Checkout
         uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
 
       - name: Initialize the build environment
         id: init
@@ -344,7 +384,7 @@ jobs:
           sudo rm -f /swapfile /mnt/swapfile
           sudo apt-get -y update
           sudo apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
-          sudo apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2604-make-openwrt-depends)
+          sudo apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
           sudo systemctl daemon-reload
           #sudo apt-get -y full-upgrade
           sudo apt-get -y autoremove --purge
@@ -377,26 +417,135 @@ jobs:
           df -Th
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Build OpenWrt rootfs [ ${{ inputs.releases_branch }} ]
-        id: imagebuilder
+      - name: Clone source code [ ${{ matrix.branch }} ]
+        id: codes
+        working-directory: /builder
         if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
         run: |
-          RELEASES_BRANCH="${{ inputs.releases_branch }}"
-          chmod +x ${IMAGEBUILDER_SH}
-          ${IMAGEBUILDER_SH} ${RELEASES_BRANCH}
-          echo "build_tag=OpenWrt_imagebuilder_${RELEASES_BRANCH/:/_}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
-          # Create symbolic link for packaging
-          [[ -d "/builder/openwrt" ]] || mkdir -p /builder/openwrt
+          # Determine the OpenWrt source code repository
+          if [[ "${{ matrix.branch }}" =~ ^openwrt ]]; then
+              REPO_URL="https://github.com/openwrt/openwrt"
+          elif [[ "${{ matrix.branch }}" =~ ^lede ]]; then
+              REPO_URL="https://github.com/17688838786/lede"
+          elif [[ "${{ matrix.branch }}" =~ ^immortalwrt ]]; then
+              REPO_URL="https://github.com/immortalwrt/immortalwrt"
+          else
+              echo "Error: Unknown source code repository."
+              exit 1
+          fi
+          source_branch_input="${{ matrix.branch }}"
+          REPO_NAME="${source_branch_input%_*}"
+          REPO_BRANCH="${source_branch_input##*_}"
+
+          # Clone the source code repository
+          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
+          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt
           ln -sf /builder/openwrt /home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt
+
+          # Export build metadata
+          echo "build_tag=OpenWrt_${{ matrix.branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
+          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
+          df -hT ${PWD}
+          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
+          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
+          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Load custom feeds
+        run: |
+          [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
+          chmod +x ${DIY_P1_SH}
+          cd openwrt/
+          ${{ github.workspace }}/${DIY_P1_SH}
+
+      - name: Update feeds
+        run: cd openwrt/ && ./scripts/feeds update -a
+
+      - name: Install feeds
+        run: cd openwrt/ && ./scripts/feeds install -a
+
+      - name: Load custom configuration
+        run: |
+          [[ -d "files" ]] && mv -f files openwrt/files
+          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
+          chmod +x ${DIY_P2_SH}
+          cd openwrt/
+          ${{ github.workspace }}/${DIY_P2_SH} "${{ inputs.openwrt_ip }}" "${{ inputs.use_ccache }}"
+
+      - name: Download package
+        id: package
+        run: |
+          cd openwrt/
+          make defconfig
+          make download -j8
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
+
+      - name: Get OpenWrt source commit hash
+        id: openwrthash
+        run: |
+          # Get the latest source hash from the kernel repository
+          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
+          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
+          source_hash=$(curl -fsSL -m 20 \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              ${api_url} |
+              jq -r '.object.sha'
+          )
+          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
+          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Cache ccache
+        uses: actions/cache@v5
+        with:
+          path: /builder/openwrt/.ccache
+          key: openwrt-${{ env.REPO_NAME }}-${{ env.source_hash }}
+          restore-keys: |
+            openwrt-${{ env.REPO_NAME }}-
+
+      - name: Compile the OpenWrt firmware
+        id: compile
+        run: |
+          cd openwrt/
+          echo -e "Compiling with $(nproc) threads"
+          make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
+
+          echo -e "ccache statistics:"
+          ccache -s 2>/dev/null
+          echo -e "ccache directory size:"
+          du -sh $(pwd)/.ccache 2>/dev/null || echo "No ccache directory found."
+
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Clean up build files and reclaim disk space
+        id: clean
+        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
+        continue-on-error: true
+        run: |
+          set +e
+          sync
+          sleep 6
+          cd openwrt/
+          [[ -d "output" ]] || mkdir output
+          ls -alh bin/targets/*/*/* || true
+          cp -f bin/targets/*/*/*-generic-rootfs.tar.gz output/
+          cp -f .config output/config
+          # 规避 xargs 返回码坑，逐个删除，不因为个别目录busy导致整体失败
+          for item in $(ls -A | grep -vE '^(output|\.ccache)$'); do
+            rm -rf "$item" 2>/dev/null
+          done
           df -hT ${PWD}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
+
       - name: Upload OpenWrt rootfs to Release
         uses: ophub/upload-to-releases@main
-        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
+        if: ${{ steps.clean.outputs.status == 'success' && !cancelled() }}
         with:
           tag: ${{ env.build_tag }}
-          artifacts: output/*
+          artifacts: openwrt/output/*
           allow_updates: true
           remove_artifacts: false
           replaces_artifacts: true
@@ -404,10 +553,10 @@ jobs:
           gh_token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Package OpenWrt for target boards
-        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
+        if: ${{ steps.clean.outputs.status == 'success' && !cancelled() }}
         uses: ophub/amlogic-s9xxx-openwrt@main
         with:
-          openwrt_path: output/*rootfs.tar.gz
+          openwrt_path: openwrt/output/*rootfs.tar.gz
           openwrt_ip: ${{ inputs.openwrt_ip }}
           openwrt_board: ${{ inputs.openwrt_board }}
           openwrt_kernel: ${{ inputs.openwrt_kernel }}
@@ -436,6 +585,8 @@ jobs:
             - Default WIFI password: `none`
             ### Install to EMMC
             - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
+            ### OpenWrt source code
+            - [${{ env.REPO_NAME }}](${{ env.REPO_URL }}/tree/${{ env.REPO_BRANCH }})
             ### Applicable Platform
             - 🐧 `arm64`
             - 🐋 Docker image: https://hub.docker.com/u/ophub
